# Pull base Image
FROM python:3.11.4-slim-buster

# Set work directory
WORKDIR  /app

#Set Environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_DISABLE_VERSION_CHECK 1
ENV PYTHONBUFFERED 1

# Lint
RUN pip install --upgrade pip
RUN pip install flake8==6.0.0
COPY . /app
RUN flake8 --ignore=E501,F401 .

#Install dependecies
COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

